# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-10-15 09:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.core.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dctsharedcontent', '0001_initial'),
        ('wagtailcore', '0040_page_draft_title'),
        ('images', '0002_pheimage_file_hash'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerPanel',
            fields=[
                ('sharedcontent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dctsharedcontent.SharedContent')),
                ('heading', models.CharField(blank=True, max_length=255, null=True)),
                ('body', wagtail.core.fields.RichTextField(blank=True, null=True)),
                ('meta_gradient', models.BooleanField(default=False, verbose_name='Green gradient')),
                ('cta_text', models.CharField(blank=True, max_length=255, null=True)),
                ('cta_link', models.CharField(blank=True, max_length=255, null=True)),
                ('background_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.PHEImage')),
                ('cta_page', modelcluster.fields.ParentalKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='base_banner_shelf_links', to='wagtailcore.Page')),
            ],
            bases=('dctsharedcontent.sharedcontent',),
        ),
    ]
