# Generated by Django 2.1.2 on 2018-11-27 15:41

import dctcmsbase.blocks
from django.db import migrations, models
import django.db.models.deletion
import shelves.blocks
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('dctsharedcontent', '0002_auto_20181016_1143'),
        ('dctcmsbase', '0003_auto_20181018_1234'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promo',
            fields=[
                ('sharedcontent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dctsharedcontent.SharedContent')),
                ('heading', models.CharField(blank=True, max_length=255, null=True)),
                ('attributes', wagtail.core.fields.StreamField([('background_image', wagtail.core.blocks.StructBlock([('image', shelves.blocks.BlobImageChooserBlock(required=False)), ('meta_variant', wagtail.core.blocks.ChoiceBlock(choices=[('none', 'None'), ('gradient', 'Background Gradient')], classname='dct-meta-field', label='Variant')), ('meta_mobile_rendition', wagtail.core.blocks.ChoiceBlock(choices=[('none', 'Use Original'), ('107x176', '107 x 176'), ('107x370', '107 x 370'), ('120x120', '120 x 120'), ('121x176', '121 x 176'), ('121x326', '121 x 326'), ('132x176', '132 x 176'), ('132x334', '132 x 334'), ('136x117', '136 x 117 Sexhealth information'), ('138x176', '138 x 176'), ('158x145', '158 x 145'), ('173x176', '173 x 176'), ('188x176', '188 x 176'), ('305x120', '305 x 120'), ('320x540', '320 x 540 Sexhealth home page header'), ('345x160', '345 x 160'), ('360x180', '360 x 180 Sexhealth teaser'), ('375x143', '375 x 143'), ('375x200', '375 x 200 Sexhealth page header, banner/promo background'), ('375x256', '375 x 256'), ('375x307', '375 x 307')], classname='dct-meta-field', label='Mobile Rendition')), ('meta_desktop_rendition', wagtail.core.blocks.ChoiceBlock(choices=[('none', 'Use Original'), ('128x263', '128 x 263'), ('128x378', '128 x 378'), ('146x336', '146 x 336'), ('180x360', '180 x 360 Sexhealth teaser'), ('182x378', '182 x 378'), ('196x263', '196 x 263'), ('196x289', '196 x 289'), ('200x200', '200 x 200'), ('224x336', '224 x 336'), ('258x220', '258 x 220'), ('280x289', '280 x 289'), ('287x263', '287 x 263'), ('364x220', '364 x 220'), ('403x263', '403 x 263'), ('408x351', '408 x 351 Sexhealth information'), ('410x263', '410 x 263'), ('460x336', '460 x 336'), ('504x263', '504 x 263'), ('560x220', '560 x 220'), ('575x263', '575 x 263'), ('650x450', '650 x 450'), ('720x263', '720 x 263'), ('1366x591', '1366 x 591 Sexhealth home page header background'), ('1440x240', '1440 x 240'), ('1440x309', '1440 x 309'), ('1440x366', '1440 x 366 Sexhealth page header, banner/promo background'), ('1440x800', '1440 x 800'), ('1150x220', '1150 x 220')], classname='dct-meta-field', label='Desktop Rendition')), ('meta_image_display', wagtail.core.blocks.ChoiceBlock(choices=[('contain', 'Contain'), ('cover', 'Stretch')], classname='dct-meta-field', label='Image Display'))]))], blank=True, null=True)),
                ('ctas', wagtail.core.fields.StreamField([('cta', wagtail.core.blocks.StructBlock([('link_text', wagtail.core.blocks.CharBlock(required=False)), ('link_external', wagtail.core.blocks.CharBlock(label='External link', required=False)), ('link_page', dctcmsbase.blocks.ItemPageBlock(required=False)), ('link_id', dctcmsbase.blocks.IDBlock(classname='dct-meta-field', help_text='Uniquely identify the CTA. Often used for tracking', label='ID', required=False)), ('meta_cta_variant', wagtail.core.blocks.ChoiceBlock(choices=[('link', 'Link'), ('button', 'Button')], classname='dct-meta-field', label='CTA Style'))]))], blank=True, null=True)),
            ],
            bases=('dctsharedcontent.sharedcontent',),
        ),
        migrations.RemoveField(
            model_name='banner',
            name='background_image',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='background_image_desktop_rendition',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='background_image_mobile_rendition',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='cta_link',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='cta_page',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='cta_text',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='meta_variant',
        ),
        migrations.AddField(
            model_name='banner',
            name='attributes',
            field=wagtail.core.fields.StreamField([('background_image', wagtail.core.blocks.StructBlock([('image', shelves.blocks.BlobImageChooserBlock(required=False)), ('meta_variant', wagtail.core.blocks.ChoiceBlock(choices=[('none', 'None'), ('gradient', 'Background Gradient')], classname='dct-meta-field', label='Variant')), ('meta_mobile_rendition', wagtail.core.blocks.ChoiceBlock(choices=[('none', 'Use Original'), ('107x176', '107 x 176'), ('107x370', '107 x 370'), ('120x120', '120 x 120'), ('121x176', '121 x 176'), ('121x326', '121 x 326'), ('132x176', '132 x 176'), ('132x334', '132 x 334'), ('136x117', '136 x 117 Sexhealth information'), ('138x176', '138 x 176'), ('158x145', '158 x 145'), ('173x176', '173 x 176'), ('188x176', '188 x 176'), ('305x120', '305 x 120'), ('320x540', '320 x 540 Sexhealth home page header'), ('345x160', '345 x 160'), ('360x180', '360 x 180 Sexhealth teaser'), ('375x143', '375 x 143'), ('375x200', '375 x 200 Sexhealth page header, banner/promo background'), ('375x256', '375 x 256'), ('375x307', '375 x 307')], classname='dct-meta-field', label='Mobile Rendition')), ('meta_desktop_rendition', wagtail.core.blocks.ChoiceBlock(choices=[('none', 'Use Original'), ('128x263', '128 x 263'), ('128x378', '128 x 378'), ('146x336', '146 x 336'), ('180x360', '180 x 360 Sexhealth teaser'), ('182x378', '182 x 378'), ('196x263', '196 x 263'), ('196x289', '196 x 289'), ('200x200', '200 x 200'), ('224x336', '224 x 336'), ('258x220', '258 x 220'), ('280x289', '280 x 289'), ('287x263', '287 x 263'), ('364x220', '364 x 220'), ('403x263', '403 x 263'), ('408x351', '408 x 351 Sexhealth information'), ('410x263', '410 x 263'), ('460x336', '460 x 336'), ('504x263', '504 x 263'), ('560x220', '560 x 220'), ('575x263', '575 x 263'), ('650x450', '650 x 450'), ('720x263', '720 x 263'), ('1366x591', '1366 x 591 Sexhealth home page header background'), ('1440x240', '1440 x 240'), ('1440x309', '1440 x 309'), ('1440x366', '1440 x 366 Sexhealth page header, banner/promo background'), ('1440x800', '1440 x 800'), ('1150x220', '1150 x 220')], classname='dct-meta-field', label='Desktop Rendition')), ('meta_image_display', wagtail.core.blocks.ChoiceBlock(choices=[('contain', 'Contain'), ('cover', 'Stretch')], classname='dct-meta-field', label='Image Display'))]))], blank=True, null=True),
        ),
        migrations.AddField(
            model_name='banner',
            name='ctas',
            field=wagtail.core.fields.StreamField([('cta', wagtail.core.blocks.StructBlock([('link_text', wagtail.core.blocks.CharBlock(required=False)), ('link_external', wagtail.core.blocks.CharBlock(label='External link', required=False)), ('link_page', dctcmsbase.blocks.ItemPageBlock(required=False)), ('link_id', dctcmsbase.blocks.IDBlock(classname='dct-meta-field', help_text='Uniquely identify the CTA. Often used for tracking', label='ID', required=False)), ('meta_cta_variant', wagtail.core.blocks.ChoiceBlock(choices=[('link', 'Link'), ('button', 'Button')], classname='dct-meta-field', label='CTA Style'))]))], blank=True, null=True),
        ),
    ]
