# Generated by Django 2.1.2 on 2018-12-17 14:27

import dctcmsbase.blocks
from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('dctsharedcontent', '0002_auto_20181016_1143'),
        ('dctcmsbase', '0004_auto_20181127_1541'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppTeaser',
            fields=[
                ('sharedcontent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dctsharedcontent.SharedContent')),
                ('heading', models.CharField(blank=True, max_length=255, null=True)),
                ('body', wagtail.core.fields.RichTextField(blank=True, null=True)),
                ('attributes', wagtail.core.fields.StreamField([('image', wagtail.core.blocks.StructBlock([('image', dctcmsbase.blocks.BlobImageChooserBlock(required=False)), ('meta_variant', wagtail.core.blocks.ChoiceBlock(choices=[('none', 'None'), ('gradient', 'Background Gradient')], classname='dct-meta-field', label='Variant')), ('meta_mobile_rendition', wagtail.core.blocks.ChoiceBlock(choices=[('none', 'Use Original'), ('107x176', '107 x 176 [[oneyou]]'), ('107x370', '107 x 370 [[oneyou]]'), ('120x120', '120 x 120 [[oneyou]]'), ('121x176', '121 x 176 [[oneyou]]'), ('121x326', '121 x 326 [[oneyou]]'), ('132x176', '132 x 176 [[oneyou]]'), ('132x334', '132 x 334 [[oneyou]]'), ('138x176', '138 x 176 [[oneyou]]'), ('158x145', '158 x 145 [[oneyou]]'), ('173x176', '173 x 176 [[oneyou]]'), ('188x176', '188 x 176 [[oneyou]]'), ('305x120', '305 x 120 [[oneyou]]'), ('345x160', '345 x 160 [[oneyou]]'), ('375x143', '375 x 143 [[oneyou]]'), ('375x256', '375 x 256 [[oneyou]]'), ('375x307', '375 x 307 [[oneyou]]'), ('360x180', '360 x 180 Teaser [[sexhealth]]'), ('136x117', '136 x 117 Information [[sexhealth]]'), ('320x540', '320 x 540 Home page header [[sexhealth]]'), ('375x200', '375 x 200 Page header, banner/promo background [[sexhealth]]')], classname='dct-meta-field', label='Mobile Rendition')), ('meta_desktop_rendition', wagtail.core.blocks.ChoiceBlock(choices=[('none', 'Use Original'), ('128x263', '128 x 263 [[oneyou]]'), ('128x378', '128 x 378 [[oneyou]]'), ('146x336', '146 x 336 [[oneyou]]'), ('182x378', '182 x 378 [[oneyou]]'), ('196x263', '196 x 263 [[oneyou]]'), ('196x289', '196 x 289 [[oneyou]]'), ('200x200', '200 x 200 [[oneyou]]'), ('224x336', '224 x 336 [[oneyou]]'), ('258x220', '258 x 220 [[oneyou]]'), ('280x289', '280 x 289 [[oneyou]]'), ('287x263', '287 x 263 [[oneyou]]'), ('364x220', '364 x 220 [[oneyou]]'), ('403x263', '403 x 263 [[oneyou]]'), ('410x263', '410 x 263 [[oneyou]]'), ('460x336', '460 x 336 [[oneyou]]'), ('504x263', '504 x 263 [[oneyou]]'), ('560x220', '560 x 220 [[oneyou]]'), ('575x263', '575 x 263 [[oneyou]]'), ('650x450', '650 x 450 [[oneyou]]'), ('720x263', '720 x 263 [[oneyou]]'), ('1440x240', '1440 x 240 [[oneyou]]'), ('1440x309', '1440 x 309 [[oneyou]]'), ('1440x800', '1440 x 800 [[oneyou]]'), ('1150x220', '1150 x 220 [[oneyou]]'), ('180x360', '180 x 360 Teaser [[sexhealth]]'), ('408x351', '408 x 351 Information [[sexhealth]]'), ('1366x591', '1366 x 591 Home page header background [[sexhealth]]'), ('1440x366', '1440 x 366 Page header, banner/promo background [[sexhealth]]')], classname='dct-meta-field', label='Desktop Rendition'))]))], blank=True, null=True)),
                ('ctas', wagtail.core.fields.StreamField([('cta', wagtail.core.blocks.StructBlock([('link_text', wagtail.core.blocks.CharBlock(required=False)), ('link_external', wagtail.core.blocks.CharBlock(label='External link', required=False)), ('link_page', dctcmsbase.blocks.ItemPageBlock(required=False)), ('link_id', dctcmsbase.blocks.IDBlock(classname='dct-meta-field', help_text='Uniquely identify the CTA. Often used for tracking', label='ID', required=False)), ('meta_cta_variant', wagtail.core.blocks.ChoiceBlock(choices=[('link', 'Link'), ('button', 'Button')], classname='dct-meta-field', label='CTA Style'))]))], blank=True, null=True)),
                ('cta_googleplay', models.URLField(blank=True, max_length=255, null=True)),
                ('cta_appstore', models.URLField(blank=True, max_length=255, null=True)),
            ],
            bases=('dctsharedcontent.sharedcontent',),
        ),
        migrations.RemoveField(
            model_name='promo',
            name='sharedcontent_ptr',
        ),
        migrations.AlterField(
            model_name='banner',
            name='attributes',
            field=wagtail.core.fields.StreamField([('background_image', wagtail.core.blocks.StructBlock([('image', dctcmsbase.blocks.BlobImageChooserBlock(required=False)), ('meta_variant', wagtail.core.blocks.ChoiceBlock(choices=[('none', 'None'), ('gradient', 'Background Gradient')], classname='dct-meta-field', label='Variant')), ('meta_mobile_rendition', wagtail.core.blocks.ChoiceBlock(choices=[('none', 'Use Original'), ('107x176', '107 x 176 [[oneyou]]'), ('107x370', '107 x 370 [[oneyou]]'), ('120x120', '120 x 120 [[oneyou]]'), ('121x176', '121 x 176 [[oneyou]]'), ('121x326', '121 x 326 [[oneyou]]'), ('132x176', '132 x 176 [[oneyou]]'), ('132x334', '132 x 334 [[oneyou]]'), ('138x176', '138 x 176 [[oneyou]]'), ('158x145', '158 x 145 [[oneyou]]'), ('173x176', '173 x 176 [[oneyou]]'), ('188x176', '188 x 176 [[oneyou]]'), ('305x120', '305 x 120 [[oneyou]]'), ('345x160', '345 x 160 [[oneyou]]'), ('375x143', '375 x 143 [[oneyou]]'), ('375x256', '375 x 256 [[oneyou]]'), ('375x307', '375 x 307 [[oneyou]]'), ('360x180', '360 x 180 Teaser [[sexhealth]]'), ('136x117', '136 x 117 Information [[sexhealth]]'), ('320x540', '320 x 540 Home page header [[sexhealth]]'), ('375x200', '375 x 200 Page header, banner/promo background [[sexhealth]]')], classname='dct-meta-field', label='Mobile Rendition')), ('meta_desktop_rendition', wagtail.core.blocks.ChoiceBlock(choices=[('none', 'Use Original'), ('128x263', '128 x 263 [[oneyou]]'), ('128x378', '128 x 378 [[oneyou]]'), ('146x336', '146 x 336 [[oneyou]]'), ('182x378', '182 x 378 [[oneyou]]'), ('196x263', '196 x 263 [[oneyou]]'), ('196x289', '196 x 289 [[oneyou]]'), ('200x200', '200 x 200 [[oneyou]]'), ('224x336', '224 x 336 [[oneyou]]'), ('258x220', '258 x 220 [[oneyou]]'), ('280x289', '280 x 289 [[oneyou]]'), ('287x263', '287 x 263 [[oneyou]]'), ('364x220', '364 x 220 [[oneyou]]'), ('403x263', '403 x 263 [[oneyou]]'), ('410x263', '410 x 263 [[oneyou]]'), ('460x336', '460 x 336 [[oneyou]]'), ('504x263', '504 x 263 [[oneyou]]'), ('560x220', '560 x 220 [[oneyou]]'), ('575x263', '575 x 263 [[oneyou]]'), ('650x450', '650 x 450 [[oneyou]]'), ('720x263', '720 x 263 [[oneyou]]'), ('1440x240', '1440 x 240 [[oneyou]]'), ('1440x309', '1440 x 309 [[oneyou]]'), ('1440x800', '1440 x 800 [[oneyou]]'), ('1150x220', '1150 x 220 [[oneyou]]'), ('180x360', '180 x 360 Teaser [[sexhealth]]'), ('408x351', '408 x 351 Information [[sexhealth]]'), ('1366x591', '1366 x 591 Home page header background [[sexhealth]]'), ('1440x366', '1440 x 366 Page header, banner/promo background [[sexhealth]]')], classname='dct-meta-field', label='Desktop Rendition')), ('meta_image_display', wagtail.core.blocks.ChoiceBlock(choices=[('contain', 'Contain'), ('cover', 'Stretch')], classname='dct-meta-field', label='Image Display'))]))], blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Promo',
        ),
    ]
