version: '2'

services:

  django:
    scale: $INITIAL_CONTAINER_SCALE
    start_on_create: true
    health_check:
      response_timeout: 5000
      healthy_threshold: 2
      port: 8000
      unhealthy_threshold: 3
      initializing_timeout: 120000
      interval: 20000
      strategy: recreate
      request_line: GET "/admin/"  "HTTP/1.1"
      reinitializing_timeout: 120000


  initializer:
    scale: 1
    start_on_create: true
