# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-10-15 09:46
from __future__ import unicode_literals

import dctsharedcontent.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.core.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wagtailcore', '0040_page_draft_title'),
        ('images', '0002_pheimage_file_hash'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='SharedContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shelf_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='ID')),
                ('tracking_group', models.CharField(blank=True, help_text='The tracking group, eg. EMM or OY', max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SharedContentRevision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, verbose_name='created at')),
                ('content_json', models.TextField(verbose_name='content JSON')),
            ],
        ),
        migrations.CreateModel(
            name='BannerShelf',
            fields=[
                ('sharedcontent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dctsharedcontent.SharedContent')),
                ('heading', models.CharField(blank=True, max_length=255, null=True)),
                ('body', wagtail.core.fields.RichTextField(blank=True, null=True)),
                ('meta_gradient', models.BooleanField(default=False, verbose_name='Green gradient')),
                ('cta_text', models.CharField(blank=True, max_length=255, null=True)),
                ('cta_link', models.CharField(blank=True, max_length=255, null=True)),
                ('background_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.PHEImage')),
                ('cta_page', modelcluster.fields.ParentalKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shared_content_banner_shelf_links', to='wagtailcore.Page')),
            ],
            bases=('dctsharedcontent.sharedcontent',),
        ),
        migrations.AddField(
            model_name='sharedcontentrevision',
            name='shelf',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='dctsharedcontent.SharedContent', verbose_name='shelf'),
        ),
        migrations.AddField(
            model_name='sharedcontentrevision',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AddField(
            model_name='sharedcontent',
            name='content_type',
            field=models.ForeignKey(editable=False, on_delete=models.SET(dctsharedcontent.models.get_default_shelf_content_type), related_name='shared_content', to='contenttypes.ContentType', verbose_name='content type'),
        ),
        migrations.AddField(
            model_name='sharedcontent',
            name='live_revision',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='dctsharedcontent.SharedContentRevision', verbose_name='live revision'),
        ),
    ]
