# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-10-16 10:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dctsharedcontent', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bannershelf',
            name='background_image',
        ),
        migrations.RemoveField(
            model_name='bannershelf',
            name='cta_page',
        ),
        migrations.RemoveField(
            model_name='bannershelf',
            name='sharedcontent_ptr',
        ),
        migrations.DeleteModel(
            name='BannerShelf',
        ),
    ]
