# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-06 12:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_release'),
    ]

    operations = [
        migrations.AddField(
            model_name='release',
            name='release_name',
            field=models.CharField(default='', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
