# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-13 11:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_header'),
        ('home', '0006_sitesettings_footer'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='header',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='pages.Header'),
        ),
    ]
