# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-08 10:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20180306_1056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='key',
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='uid',
            field=models.SlugField(default='oneyou', help_text='An id which can be used to lookup the site in the API', unique=True, verbose_name='Site name'),
            preserve_default=False,
        ),
    ]
