# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-10-10 15:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20180308_1032'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='adobe_tracking_url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='cookiebot_id',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='global_google_tag_manager_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='google_site_verification_id',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='google_tag_manager_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
