# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-10-11 09:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_sitesettings_favicon'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='page_types',
            field=models.ManyToManyField(blank=True, to='home.PageType'),
        ),
    ]
