# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-10-11 14:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20181011_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagetype',
            name='app',
            field=models.CharField(default='pages', max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='pagetype',
            unique_together=set([('app', 'label')]),
        ),
    ]
