# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-10-15 10:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_auto_20181011_1506'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PageType',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='page_types',
        ),
    ]
