# Generated by Django 2.1.2 on 2018-11-06 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_auto_20181015_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='adobe_datalayer_url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
