# Generated by Django 2.1.2 on 2018-12-17 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_sitesettings_adobe_datalayer_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='adobe_datalayer_url',
        ),
    ]
