# Generated by Django 2.1.4 on 2019-01-09 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_sitesettings_rendition'),
        ('home', '0017_remove_sitesettings_adobe_datalayer_url'),
    ]

    operations = [
    ]
