# Generated by Django 2.1.4 on 2019-01-29 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dctcmsbase', '0006_footer_header_menu_theme'),
        ('home', '0018_merge_20190109_1038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='footer',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='header',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='menu',
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='site_footer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='dctcmsbase.Footer'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='site_header',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='dctcmsbase.Header'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='site_menu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='dctcmsbase.Menu'),
        ),
    ]
