# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-06 13:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('release', '0001_release_release_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='release',
            name='release_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
