# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-06 15:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('release', '0002_release_release_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='release',
            name='uuid',
            field=models.CharField(default='9yg24t0hnhwpigwr094j6ykjdt6i7i968', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
