# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-28 09:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0040_page_draft_title'),
        ('release', '0003_release_uuid'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReleasePage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('release', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='release.Release')),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='release', to='wagtailcore.PageRevision')),
            ],
        ),
    ]
