# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-01 17:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('release', '0004_releasepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='release',
            name='content',
            field=models.TextField(null=True),
        ),
    ]
