# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-05 09:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('release', '0005_release_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='release',
            name='base_release',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parent', to='release.Release'),
        ),
    ]
