# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-06 17:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('release', '0007_auto_20180305_1141'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReleaseContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='release',
            name='content',
        ),
        migrations.AddField(
            model_name='releasecontent',
            name='release',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content', to='release.Release'),
        ),
    ]
