# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-08 11:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('release', '0008_auto_20180306_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='release',
            name='frontend_id',
            field=models.CharField(default=1, max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
