# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-08 12:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0040_page_draft_title'),
        ('release', '0009_release_frontend_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='release',
            name='site',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='releases', to='wagtailcore.Site'),
            preserve_default=False,
        ),
    ]
