# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-19 14:04
from __future__ import unicode_literals

from django.db import migrations, models
import release.models


class Migration(migrations.Migration):

    dependencies = [
        ('release', '0010_release_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='release',
            name='content_status',
            field=models.IntegerField(choices=[(0, 'PENDING'), (1, 'FROZEN')], default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='release',
            name='release_time',
            field=models.DateTimeField(blank=True, null=True, validators=[release.models.validate_in_future]),
        ),
    ]
