# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-05-23 09:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('release', '0012_auto_20180509_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='release',
            name='frontend_id',
            field=models.CharField(default='1234', max_length=255),
        ),
    ]
