# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-05-17 16:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('release', '0014_auto_20180514_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='release',
            name='frontend_id',
            field=models.CharField(default='d9736b1c-70f1-4d00-a497-dde55bb52c7c', max_length=255),
        ),
    ]
