# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-05-29 12:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('release', '0015_auto_20180517_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='release',
            name='frontend_id',
            field=models.CharField(choices=[('c4ff8646-a4dc-403b-8a2e-57d4374e0f5a', 'v1.0.22\n - Tue, 29 May 2018 12:27:13 GMT'), ('8272dc29-cd1e-4662-9699-b25736fba725', 'v1.0.22\n - Tue, 29 May 2018 11:51:47 GMT'), ('279be089-3c67-493f-8eba-6fff345e1f5a', 'v1.0.22\n - Tue, 29 May 2018 11:43:52 GMT'), ('329ff6c7-a771-4640-8324-470824359fd0', 'v1.0.21\n - Tue, 29 May 2018 11:23:31 GMT'), ('14205b98-b6b1-4e5a-9c18-9fb57509098b', 'v1.0.22\n - Tue, 29 May 2018 11:10:25 GMT'), ('688d9d92-c277-4e95-a41d-bf59f53909f7', 'v1.0.21\n - Fri, 25 May 2018 11:13:13 GMT'), ('a5671ef7-6d36-4231-806c-b60746191c16', 'v1.0.20\n - Fri, 25 May 2018 10:55:15 GMT'), ('086f5a98-2bc5-4543-a5ea-142c059666e6', 'v1.0.19\n - Fri, 25 May 2018 09:06:59 GMT'), ('43fea416-2070-4d30-a578-6b76affd5fc0', 'v1.0.20\n - Thu, 24 May 2018 14:41:50 GMT'), ('2be767fd-3d96-404e-b71b-88af783762c3', 'v1.0.19\n - Thu, 24 May 2018 14:22:37 GMT'), ('e7575140-391b-441b-b521-afcdfe0f5b9a', 'v1.0.19\n - Thu, 24 May 2018 14:12:05 GMT'), ('6ca84718-1ce0-4962-9da0-f3fa7fb9f8d4', 'v1.0.19\n - Thu, 24 May 2018 13:59:20 GMT'), ('8287a2c6-ffce-43bc-aa86-2838fbf4cf94', 'v1.0.19\n - Thu, 24 May 2018 12:51:34 GMT'), ('18bac9a6-092e-4df5-9255-679515c291b2', 'v1.0.19\n - Thu, 24 May 2018 12:51:22 GMT'), ('cbc504fd-bca3-4629-8805-45393adaee8f', 'v1.0.19\n - Thu, 24 May 2018 12:51:06 GMT'), ('3defb302-a3ca-4dac-94d3-851275a8791d', 'v1.0.19\n - Thu, 24 May 2018 12:06:06 GMT'), ('8f14cb81-ed32-4164-8c0b-7a32a00ef79c', 'v1.0.19\n - Thu, 24 May 2018 11:29:36 GMT'), ('858fb152-1e4e-4733-bb98-cec62efcbe0d', 'v1.0.19\n - Thu, 24 May 2018 11:29:25 GMT'), ('d002f0f7-b089-4619-a3e0-077a623e75c3', 'v1.0.19\n - Thu, 24 May 2018 11:29:10 GMT'), ('39bc36b3-6ac1-4d04-86cd-68d081c45fc9', 'v1.0.19\n - Thu, 24 May 2018 11:08:08 GMT')], default='c4ff8646-a4dc-403b-8a2e-57d4374e0f5a', max_length=255),
        ),
    ]
