# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-05-23 15:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('release', '0015_auto_20180517_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='release',
            name='frontend_id',
            field=models.CharField(choices=[('5fc9751c-539d-4d7b-8301-9cb74810f228', 'v1.0.19\n - Wed, 23 May 2018 15:24:53 GMT'), ('541aadb2-4620-45cd-9cc8-bdb365c8a05c', 'v1.0.19\n - Wed, 23 May 2018 14:57:16 GMT'), ('6ffc3f59-c3be-464d-adea-8af12497cc91', 'v1.0.19\n - Wed, 23 May 2018 14:57:06 GMT'), ('058524b7-bec6-406e-915a-decbad21da76', 'v1.0.19\n - Wed, 23 May 2018 14:56:52 GMT'), ('e1aa8e27-b27c-4188-9990-789735c85869', 'v1.0.19\n - Wed, 23 May 2018 14:28:25 GMT'), ('5e234e0a-6901-4970-be20-c2ba75f899bf', 'v1.0.19\n - Wed, 23 May 2018 13:48:21 GMT'), ('2528d732-365e-4ce3-bdb1-8ec00ecc6009', 'v1.0.19\n - Wed, 23 May 2018 13:48:11 GMT'), ('28ae565f-cc53-434c-a7f2-52502cb93a33', 'v1.0.19\n - Wed, 23 May 2018 13:47:59 GMT'), ('f8f3d315-6624-4912-b2c8-1cdacb35a8ad', 'v1.0.19\n - Wed, 23 May 2018 13:15:05 GMT'), ('9f6d9f3c-3648-4a52-9d56-2fb34f272c75', 'v1.0.19\n - Wed, 23 May 2018 13:14:56 GMT'), ('7966757a-1582-4cd0-8e0a-e9ce0ff6fc7d', 'v1.0.19\n - Wed, 23 May 2018 13:14:45 GMT'), ('6d1f3377-2267-4d8d-af17-69c3fa7a0186', 'v1.0.19\n - Wed, 23 May 2018 11:30:21 GMT'), ('2758e910-356d-404f-b389-9784dbc3bc93', 'v1.0.19\n - Wed, 23 May 2018 11:30:11 GMT'), ('af2dfd99-1c51-4c86-bcb6-ef3e3a8505e0', 'v1.0.19\n - Wed, 23 May 2018 11:30:00 GMT'), ('35c1ff50-4892-49bc-82c9-60a6a65c80f4', 'v1.0.19\n - Wed, 23 May 2018 11:16:20 GMT'), ('df3aaa6b-0ed0-499b-bacb-2cdad2d8ad7d', 'v1.0.19\n - Wed, 23 May 2018 11:16:13 GMT'), ('dc09aeeb-8392-4b8b-bfd6-e1a24094af50', 'v1.0.19\n - Wed, 23 May 2018 11:16:01 GMT'), ('fe31ab82-4c18-498c-bb1f-cf6c2b2e7e5b', 'v1.0.19\n - Wed, 23 May 2018 11:04:27 GMT'), ('94ac1075-bcec-4883-add8-6760cc23563f', 'v1.0.19\n - Wed, 23 May 2018 11:04:19 GMT'), ('d47abf64-554c-43cb-ab94-9e2d8b7e4205', 'v1.0.19\n - Wed, 23 May 2018 11:04:08 GMT')], default='5fc9751c-539d-4d7b-8301-9cb74810f228', max_length=255),
        ),
    ]
