# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-05-30 13:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('release', '0017_auto_20180530_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='release',
            name='frontend_id',
            field=models.CharField(choices=[('06afe1d5-628e-4620-85b7-1f99227abb88', 'v1.0.22\n - Wed, 30 May 2018 12:58:46 GMT'), ('57a3457f-c84a-4b13-8423-7e4ded335ba6', 'v1.0.22\n - Wed, 30 May 2018 11:01:51 GMT'), ('77e7603a-90ce-4f98-be6d-5a29d673b001', 'v1.0.22\n - Wed, 30 May 2018 10:59:36 GMT'), ('06e766a0-fd99-489f-9d0c-0c2ee29030c0', 'v1.0.22\n - Wed, 30 May 2018 10:14:08 GMT'), ('9591b81b-f39e-4372-b41d-96f5379ec5ec', 'v1.0.22\n - Wed, 30 May 2018 09:53:06 GMT'), ('efd0ca14-6f49-476f-95b5-2ae306146718', 'v1.0.22\n - Wed, 30 May 2018 08:59:41 GMT'), ('59345ae1-5950-4aad-964f-bc2f7e4bac59', 'v1.0.22\n - Tue, 29 May 2018 23:19:01 GMT'), ('c4ff8646-a4dc-403b-8a2e-57d4374e0f5a', 'v1.0.22\n - Tue, 29 May 2018 12:27:13 GMT'), ('8272dc29-cd1e-4662-9699-b25736fba725', 'v1.0.22\n - Tue, 29 May 2018 11:51:47 GMT'), ('279be089-3c67-493f-8eba-6fff345e1f5a', 'v1.0.22\n - Tue, 29 May 2018 11:43:52 GMT'), ('329ff6c7-a771-4640-8324-470824359fd0', 'v1.0.21\n - Tue, 29 May 2018 11:23:31 GMT'), ('14205b98-b6b1-4e5a-9c18-9fb57509098b', 'v1.0.22\n - Tue, 29 May 2018 11:10:25 GMT'), ('688d9d92-c277-4e95-a41d-bf59f53909f7', 'v1.0.21\n - Fri, 25 May 2018 11:13:13 GMT'), ('a5671ef7-6d36-4231-806c-b60746191c16', 'v1.0.20\n - Fri, 25 May 2018 10:55:15 GMT'), ('086f5a98-2bc5-4543-a5ea-142c059666e6', 'v1.0.19\n - Fri, 25 May 2018 09:06:59 GMT'), ('43fea416-2070-4d30-a578-6b76affd5fc0', 'v1.0.20\n - Thu, 24 May 2018 14:41:50 GMT'), ('2be767fd-3d96-404e-b71b-88af783762c3', 'v1.0.19\n - Thu, 24 May 2018 14:22:37 GMT'), ('e7575140-391b-441b-b521-afcdfe0f5b9a', 'v1.0.19\n - Thu, 24 May 2018 14:12:05 GMT'), ('6ca84718-1ce0-4962-9da0-f3fa7fb9f8d4', 'v1.0.19\n - Thu, 24 May 2018 13:59:20 GMT'), ('8287a2c6-ffce-43bc-aa86-2838fbf4cf94', 'v1.0.19\n - Thu, 24 May 2018 12:51:34 GMT')], default='06afe1d5-628e-4620-85b7-1f99227abb88', max_length=255),
        ),
    ]
