# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-06-01 09:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('release', '0016_auto_20180523_1625'),
        ('release', '0018_auto_20180530_1407'),
    ]

    operations = [
    ]
