# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-06-01 12:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('release', '0019_merge_20180601_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='release',
            name='frontend_id',
            field=models.CharField(choices=[('51038373-f973-4d62-8308-0bb64ae430f6', 'v1.1.3\n - Fri, 01 Jun 2018 12:28:56 GMT'), ('ac63e222-fd30-4c1f-970d-3e44c9e88bab', 'v1.1.3\n - Fri, 01 Jun 2018 12:25:20 GMT'), ('f1b7ac26-c7f3-484a-8ea0-e0f50e89b26e', 'v1.1.3\n - Fri, 01 Jun 2018 12:24:59 GMT'), ('88acb199-3adf-4d20-a8f6-72d2141b6d45', 'v1.1.1\n - Fri, 01 Jun 2018 12:16:26 GMT'), ('225ad106-cf90-4200-a88c-1b086a2e3c4b', 'v1.1.1\n - Fri, 01 Jun 2018 11:58:42 GMT'), ('e13a41b9-5c88-4c27-aff5-fbc2fab4b31d', 'v1.1.1\n - Fri, 01 Jun 2018 11:04:31 GMT'), ('9c4b9003-6640-4c8f-b84a-1b87c3dbd0f0', 'v1.1.1\n - Fri, 01 Jun 2018 10:48:25 GMT'), ('2719efbf-3985-4618-9e29-6abd50cc38e8', 'v1.1.1\n - Fri, 01 Jun 2018 10:45:03 GMT'), ('9029a957-571a-45b9-b8ff-e6f510740aca', 'v1.1.1\n - Fri, 01 Jun 2018 10:05:16 GMT'), ('6140a6fc-343e-4d69-85ed-baa4528171ec', 'v1.1.0\n - Thu, 31 May 2018 22:57:44 GMT'), ('49622fd6-bc75-47ce-89d7-e58c2b5707f8', 'v1.1.0\n - Thu, 31 May 2018 22:43:50 GMT'), ('b16a07af-497d-4eda-b61d-aa8d84b7b6d8', 'v1.1.1\n - Thu, 31 May 2018 14:46:02 GMT'), ('445f3a8d-2e48-4e57-9241-a3176ab20f27', 'v1.1.0\n - Thu, 31 May 2018 10:28:34 GMT'), ('9720cc0e-a8cc-40bf-9255-82b001721640', 'v1.0.23\n - Thu, 31 May 2018 10:26:19 GMT'), ('b9cf3c73-190b-4a63-a23a-0615a9f4b4f4', 'v1.0.23\n - Thu, 31 May 2018 10:12:45 GMT'), ('11161dc8-4275-4e30-a983-468f6ef17e80', 'v1.0.23\n - Thu, 31 May 2018 07:47:16 GMT'), ('5d9d4b65-fa72-498c-a394-4c65b798bf60', 'v1.0.23\n - Thu, 31 May 2018 07:30:08 GMT'), ('3ef8fd14-bdf8-4ada-a420-e6c52dbd80ca', 'v1.0.23\n - Thu, 31 May 2018 07:22:39 GMT'), ('36de2b32-7809-4f5d-893b-24d6ddf9084c', 'v1.0.23\n - Thu, 31 May 2018 07:18:09 GMT'), ('5afc6f2d-5b85-4a36-a20a-64b2efbf042e', 'v1.0.22\n - Wed, 30 May 2018 15:46:17 GMT')], default='51038373-f973-4d62-8308-0bb64ae430f6', max_length=255),
        ),
    ]
