# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-06-04 10:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('release', '0020_auto_20180601_1338'),
        ('release', '0016_merge_20180523_1423'),
    ]

    operations = [
    ]
