# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-06-11 14:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('release', '0020_auto_20180601_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='release',
            name='frontend_id',
            field=models.CharField(choices=[('ba1531ee-ab93-4f16-8cf0-392351ea924b', 'v1.1.6\n - Mon, 11 Jun 2018 11:13:08 GMT'), ('0854b99e-679d-4bea-b4f3-9d871b0d2057', 'v1.1.6\n - Mon, 11 Jun 2018 09:59:24 GMT'), ('90f1f4b6-5c85-4e46-bb79-cca513a59c80', 'v1.1.8\n - Wed, 06 Jun 2018 14:50:41 GMT'), ('8714cfc4-3d9c-4b5c-880b-0a7c2868c31d', 'v1.1.7\n - Wed, 06 Jun 2018 14:26:27 GMT'), ('a32aa938-e482-44a8-b8c5-c8df5fde3820', 'v1.1.7\n - Wed, 06 Jun 2018 14:14:01 GMT'), ('1a918001-8274-4381-855c-9c7ffe67d938', 'v1.1.6\n - Wed, 06 Jun 2018 14:04:12 GMT'), ('ae25670b-4fe9-4364-a9a4-ee86e26814a1', 'v1.1.6\n - Wed, 06 Jun 2018 09:44:54 GMT'), ('24d0b4ee-9833-4239-866e-16b806bb4a47', 'v1.1.7\n - Tue, 05 Jun 2018 15:56:28 GMT'), ('ba205a8a-304f-4519-b81a-91a3a85e7b48', 'v1.1.6\n - Tue, 05 Jun 2018 15:42:55 GMT'), ('757a6b27-065b-41f3-82ea-0c56728321af', 'v1.1.6\n - Tue, 05 Jun 2018 15:40:38 GMT'), ('9d3179b8-4f2f-419d-a318-d9fc0c7e87d4', 'v1.1.6\n - Tue, 05 Jun 2018 15:29:47 GMT'), ('9f64204c-b082-4efd-9c82-2f03b7d61bcf', 'v1.1.5\n - Tue, 05 Jun 2018 15:27:27 GMT'), ('bef050aa-6049-44d6-92ad-d1bacba67cde', 'v1.1.5\n - Tue, 05 Jun 2018 12:15:24 GMT'), ('a19a0df3-cda1-4164-a4d0-f4e99dcc3594', 'v1.1.6\n - Tue, 05 Jun 2018 11:57:56 GMT'), ('89e27245-a90f-43b7-a4c0-a1cbef3be3b3', 'v1.1.6\n - Tue, 05 Jun 2018 11:55:57 GMT'), ('abdb0149-81b0-466e-a1aa-bae965bf8fa7', 'v1.1.6\n - Tue, 05 Jun 2018 11:10:59 GMT'), ('8e11243d-456e-4114-90ed-221e3e9c5b11', 'v1.1.6\n - Tue, 05 Jun 2018 09:32:50 GMT'), ('401c6847-9dfa-4602-9f8d-4ef22ce46690', 'v1.1.6\n - Mon, 04 Jun 2018 14:06:59 GMT'), ('24fddf22-2a76-4eeb-9ba2-1cc81b164aba', 'v1.1.5\n - Mon, 04 Jun 2018 11:42:03 GMT'), ('4250f3aa-3216-43d8-aa86-a729491b99e9', 'v1.1.5\n - Mon, 04 Jun 2018 11:02:54 GMT')], default='ba1531ee-ab93-4f16-8cf0-392351ea924b', max_length=255),
        ),
    ]
