# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-06-12 21:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('release', '0021_auto_20180611_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='release',
            name='frontend_id',
            field=models.CharField(default='cf97eb0e-b9c0-46c1-b186-defae523c658', max_length=255),
        ),
    ]
