# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-06-10 18:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('release', '0021_merge_20180604_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='release',
            name='frontend_id',
            field=models.CharField(default='90f1f4b6-5c85-4e46-bb79-cca513a59c80', max_length=255),
        ),
    ]
