# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-06-18 15:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('release', '0022_auto_20180612_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='release',
            name='frontend_id',
            field=models.CharField(default='687da257-0218-4d0e-8fd4-cac1c5f5b7f8', max_length=255),
        ),
    ]
