# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-06-26 12:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('release', '0024_auto_20180614_0920'),
        ('release', '0022_auto_20180612_2236'),
    ]

    operations = [
    ]
