# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-06-27 14:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('release', '0025_merge_20180626_1307'),
        ('release', '0023_auto_20180618_1647'),
    ]

    operations = [
    ]
