# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-06-27 14:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('release', '0026_merge_20180627_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='release',
            name='frontend_id',
            field=models.CharField(default='44523712-3818-4938-a2f8-23063b67ed83', max_length=255),
        ),
    ]
