# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-06-27 15:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('release', '0027_auto_20180627_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='release',
            name='frontend_id',
            field=models.CharField(default='362e95b7-d780-4148-ad17-6b46a8e7963d', max_length=255),
        ),
    ]
