# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-08-28 12:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('release', '0030_auto_20180726_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='release',
            name='frontend_id',
            field=models.CharField(default='test', max_length=255),
        ),
    ]
