# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-08-23 08:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('release', '0031_auto_20180817_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='release',
            name='frontend_id',
            field=models.CharField(default='b5958ee8-c303-4ab8-82b1-767a3579180e', max_length=255),
        ),
    ]
