# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-09-03 23:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('release', '0032_auto_20180823_0912'),
        ('release', '0031_auto_20180813_1124'),
    ]

    operations = [
    ]
