# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-09-07 08:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('release', '0032_auto_20180828_0052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='release',
            name='frontend_id',
            field=models.CharField(default='f6c3c1d7-ab20-4f7c-ab1a-a5ba5df090a5', max_length=255),
        ),
    ]
