# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-09-10 15:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('release', '0033_merge_20180904_0001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='release',
            name='frontend_id',
            field=models.CharField(default='c3c81ec5-5e1f-46ca-9172-45a747687958', max_length=255),
        ),
    ]
