# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-09-11 10:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('release', '0034_auto_20180910_1638'),
        ('release', '0034_merge_20180910_1759'),
    ]

    operations = [
    ]
