# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-09-11 17:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('release', '0033_auto_20180907_0955'),
        ('release', '0035_merge_20180911_1133'),
    ]

    operations = [
    ]
