# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-09-19 22:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('release', '0036_merge_20180911_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='release',
            name='frontend_id',
            field=models.CharField(default='49d3499b-38bc-4afa-92d2-bbd498e1202c', max_length=255),
        ),
    ]
