# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-09-27 10:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('release', '0037_auto_20180919_2359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='release',
            name='frontend_id',
            field=models.CharField(default='a14c9cab-7f56-4d34-bcbb-5ecc91d7c94b', max_length=255),
        ),
    ]
