# Generated by Django 2.1.4 on 2019-02-11 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('release', '0041_releasepage_submitted_for_moderation'),
    ]

    operations = [
        migrations.AddField(
            model_name='release',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
