# Generated by Django 2.1.2 on 2019-02-13 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('release', '0042_release_archived'),
    ]

    operations = [
        migrations.AlterField(
            model_name='release',
            name='release_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
