# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-07 10:33
from __future__ import unicode_literals

from django.db import migrations, models
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_auto_20180206_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='label',
            field=models.CharField(default='old menu', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='menu',
            name='menu_items',
            field=wagtail.wagtailcore.fields.StreamField((('simple_menu_item', wagtail.wagtailcore.blocks.StructBlock((('link_text', wagtail.wagtailcore.blocks.CharBlock(required=True)), ('link_external', wagtail.wagtailcore.blocks.URLBlock(label='External link', required=False)), ('link_page', wagtail.wagtailcore.blocks.PageChooserBlock(required=False))))), ('multi_menu_item', wagtail.wagtailcore.blocks.StructBlock((('label', wagtail.wagtailcore.blocks.CharBlock(required=True)), ('menu_items', wagtail.wagtailcore.blocks.StreamBlock((('simple_menu_item', wagtail.wagtailcore.blocks.StructBlock((('link_text', wagtail.wagtailcore.blocks.CharBlock(required=True)), ('link_external', wagtail.wagtailcore.blocks.URLBlock(label='External link', required=False)), ('link_page', wagtail.wagtailcore.blocks.PageChooserBlock(required=False))))),), icon='arrow-left', label='Items'))))))),
        ),
    ]
