# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-08 12:35
from __future__ import unicode_literals

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_footer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footer',
            name='follow_us',
            field=wagtail.core.fields.StreamField((('social_media_link', wagtail.core.blocks.StructBlock((('label', wagtail.core.blocks.CharBlock(required=True)), ('type', wagtail.core.blocks.ChoiceBlock(choices=[('twitter', 'Twitter'), ('facebook', 'Facebook')])), ('link', wagtail.core.blocks.URLBlock(label='External link', required=False))))),)),
        ),
    ]
