# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-12 15:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_auto_20180208_1235'),
        ('pages', '0006_oneyou2page_release'),
    ]

    operations = [
    ]
