# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-08 15:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_oneyou2page_release'),
    ]

    operations = [
        migrations.AddField(
            model_name='oneyou2page',
            name='uuid',
            field=models.CharField(default='', max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='oneyou2page',
            name='release',
            field=modelcluster.fields.ParentalKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pages', to='release.Release'),
        ),
    ]
