# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-12 15:38
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_merge_20180212_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oneyou2page',
            name='release',
            field=modelcluster.fields.ParentalKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pages', to='release.Release'),
        ),
    ]
