# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-13 14:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_auto_20180212_1252'),
    ]

    operations = [
        migrations.RenameField(
            model_name='oneyou2page',
            old_name='uuid',
            new_name='page_ref',
        ),
    ]
