# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-26 14:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0015_auto_20180216_1916'),
        ('pages', '0015_auto_20180221_1504'),
    ]

    operations = [
    ]
