# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-26 15:39
from __future__ import unicode_literals

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0016_merge_20180226_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oneyou2page',
            name='body',
            field=wagtail.core.fields.StreamField((('section_heading', wagtail.core.blocks.StructBlock((('heading', wagtail.core.blocks.CharBlock(required=True)), ('shelf_id', wagtail.core.blocks.CharBlock(help_text='Not displayed in the front end', label='ID', required=False))), classname='full title', icon='title')), ('backwards_compatible_content', wagtail.core.blocks.StructBlock((('heading', wagtail.core.blocks.CharBlock(required=True)), ('body', wagtail.core.blocks.TextBlock(required=True)), ('image', wagtail.images.blocks.ImageChooserBlock()), ('shelf_id', wagtail.core.blocks.CharBlock(label='ID', required=False))), icon='folder-inverse', label='Previous content')), ('find_out_more_dropdown', wagtail.core.blocks.StructBlock((('heading', wagtail.core.blocks.CharBlock(required=True)), ('links', wagtail.core.blocks.StreamBlock((('simple_menu_item', wagtail.core.blocks.StructBlock((('link_text', wagtail.core.blocks.CharBlock(required=True)), ('link_external', wagtail.core.blocks.URLBlock(label='External link', required=False)), ('link_page', wagtail.core.blocks.PageChooserBlock(required=False))))),), icon='arrow-left', label='Items')), ('shelf_id', wagtail.core.blocks.CharBlock(label='ID', required=False))), icon='order-down', label='Link dropdown')), ('video', wagtail.core.blocks.StructBlock((('heading', wagtail.core.blocks.CharBlock(required=True)), ('subheading', wagtail.core.blocks.CharBlock(required=True)), ('body', wagtail.core.blocks.TextBlock(required=True)), ('video', wagtail.core.blocks.CharBlock(required=True)), ('shelf_id', wagtail.core.blocks.CharBlock(label='ID', required=False))), icon='media')), ('carousel', wagtail.core.blocks.StructBlock((('items', wagtail.core.blocks.StreamBlock((('backwards_compatible_content', wagtail.core.blocks.StructBlock((('heading', wagtail.core.blocks.CharBlock(required=True)), ('body', wagtail.core.blocks.TextBlock(required=True)), ('image', wagtail.images.blocks.ImageChooserBlock()), ('shelf_id', wagtail.core.blocks.CharBlock(label='ID', required=False))), icon='folder-inverse', label='Previous content')), ('video', wagtail.core.blocks.StructBlock((('heading', wagtail.core.blocks.CharBlock(required=True)), ('subheading', wagtail.core.blocks.CharBlock(required=True)), ('body', wagtail.core.blocks.TextBlock(required=True)), ('video', wagtail.core.blocks.CharBlock(required=True)), ('shelf_id', wagtail.core.blocks.CharBlock(label='ID', required=False))), icon='media'))), icon='arrow-left', label='Items')), ('shelf_id', wagtail.core.blocks.CharBlock(label='ID', required=False))), icon='repeat')))),
        ),
    ]
