# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-27 10:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0016_merge_20180226_1451'),
        ('pages', '0017_auto_20180226_1106'),
    ]

    operations = [
    ]
