# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-27 15:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0017_auto_20180226_1539'),
        ('pages', '0018_merge_20180227_1013'),
    ]

    operations = [
    ]
