# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-27 15:02
from __future__ import unicode_literals

from django.db import migrations
import shelves.blocks
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields
import wagtail.wagtailimages.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0019_merge_20180227_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oneyou2page',
            name='body',
            field=wagtail.wagtailcore.fields.StreamField((('section_heading_shelf', wagtail.wagtailcore.blocks.StructBlock((('heading', wagtail.wagtailcore.blocks.CharBlock(required=True)), ('shelf_id', wagtail.wagtailcore.blocks.CharBlock(help_text='Not displayed in the front end', label='ID', required=False))), classname='full title', icon='title')), ('oneyou_teaser', wagtail.wagtailcore.blocks.StructBlock((('heading', wagtail.wagtailcore.blocks.CharBlock(required=True)), ('body', wagtail.wagtailcore.blocks.TextBlock(required=True)), ('image', wagtail.wagtailimages.blocks.ImageChooserBlock()), ('shelf_id', wagtail.wagtailcore.blocks.CharBlock(label='ID', required=False))), icon='folder-inverse', label='Previous content')), ('video_teaser', wagtail.wagtailcore.blocks.StructBlock((('heading', wagtail.wagtailcore.blocks.CharBlock(required=True)), ('subheading', wagtail.wagtailcore.blocks.CharBlock(required=True)), ('body', wagtail.wagtailcore.blocks.TextBlock(required=True)), ('video', wagtail.wagtailcore.blocks.CharBlock(required=True)), ('shelf_id', wagtail.wagtailcore.blocks.CharBlock(label='ID', required=False))), icon='media')), ('carousel_shelf', wagtail.wagtailcore.blocks.StructBlock((('items', wagtail.wagtailcore.blocks.StreamBlock((('backwards_compatible_content', wagtail.wagtailcore.blocks.StructBlock((('heading', wagtail.wagtailcore.blocks.CharBlock(required=True)), ('body', wagtail.wagtailcore.blocks.TextBlock(required=True)), ('image', wagtail.wagtailimages.blocks.ImageChooserBlock()), ('shelf_id', wagtail.wagtailcore.blocks.CharBlock(label='ID', required=False))), icon='folder-inverse', label='Previous content')), ('video', wagtail.wagtailcore.blocks.StructBlock((('heading', wagtail.wagtailcore.blocks.CharBlock(required=True)), ('subheading', wagtail.wagtailcore.blocks.CharBlock(required=True)), ('body', wagtail.wagtailcore.blocks.TextBlock(required=True)), ('video', wagtail.wagtailcore.blocks.CharBlock(required=True)), ('shelf_id', wagtail.wagtailcore.blocks.CharBlock(label='ID', required=False))), icon='media'))), icon='arrow-left', label='Items')), ('shelf_id', wagtail.wagtailcore.blocks.CharBlock(label='ID', required=False))), icon='repeat')), ('promo_shelf', shelves.blocks.PromoShelfChooserBlock(icon='image', target_model='shelves.PromoShelf')), ('banner_shelf', shelves.blocks.BannerShelfChooserBlock(icon='image', target_model='shelves.BannerShelf')), ('app_shelf', shelves.blocks.AppTeaserChooserBlock(icon='image', target_model='shelves.AppTeaser')))),
        ),
    ]
