# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-06 17:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0032_auto_20180306_1528'),
        ('pages', '0029_auto_20180306_1619'),
    ]

    operations = [
    ]
