# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-08 13:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0034_auto_20180308_1032'),
        ('pages', '0034_auto_20180307_1047'),
    ]

    operations = [
    ]
