# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-12 22:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0035_merge_20180308_1320'),
        ('pages', '0035_auto_20180312_1006'),
    ]

    operations = [
    ]
