# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-13 14:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0037_auto_20180313_1024'),
        ('pages', '0036_merge_20180312_2239'),
    ]

    operations = [
    ]
