# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-13 17:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0038_merge_20180313_1424'),
        ('pages', '0036_auto_20180313_1216'),
    ]

    operations = [
    ]
