# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-14 16:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0039_merge_20180313_1752'),
        ('pages', '0039_merge_20180314_1027'),
    ]

    operations = [
    ]
