# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-23 09:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0042_auto_20180319_1025'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaTags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('og_title', models.CharField(default='Change4Life - Change4Life', max_length=255)),
                ('og_description', models.CharField(default='Fun ideas, recipes, top tips and activities to help your kids stay healthy. Make a change today with Change4Life!', max_length=255)),
                ('og_url', models.CharField(default='https://www.nhs.uk/change4life', max_length=255)),
                ('og_image', models.CharField(default='https://www.nhs.uk/change4life/assets/c4l-generic-social-share-f6de41c98796bab1b40f263d13f5933cf68c295524b40ec7445aa2016aed156f.jpg', max_length=255)),
                ('og_type', models.CharField(default='website', max_length=255)),
                ('twitter_url', models.CharField(default='https://www.nhs.uk/change4life', max_length=255)),
                ('twitter_card', models.CharField(default='summary', max_length=255)),
                ('twitter_site', models.CharField(default='@Change4Life', max_length=255)),
                ('twitter_title', models.CharField(default='Change4Life - Change4Life', max_length=255)),
                ('twitter_description', models.CharField(default='Fun ideas, recipes, top tips and activities to help your kids stay healthy. Make a change today with Change4Life!', max_length=255)),
                ('twitter_image', models.CharField(default='', max_length=255)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='meta_tags', to='pages.OneYou2Page')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
