# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-25 18:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
        ('pages', '0042_auto_20180319_1025'),
    ]

    operations = [
        migrations.AddField(
            model_name='oneyou2page',
            name='og_description',
            field=models.CharField(default='Start the fight back to a healthier you! One You is packed with practical tips, tools and free apps to help you improve your health today', max_length=255),
        ),
        migrations.AddField(
            model_name='oneyou2page',
            name='og_image_fk',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.PHEImage', verbose_name='OG image'),
        ),
        migrations.AddField(
            model_name='oneyou2page',
            name='og_title',
            field=models.CharField(default='One You - Home', max_length=255),
        ),
        migrations.AddField(
            model_name='oneyou2page',
            name='og_type',
            field=models.CharField(default='website', max_length=255),
        ),
        migrations.AddField(
            model_name='oneyou2page',
            name='og_url',
            field=models.CharField(default='https://www.nhs.uk/oneyou', max_length=255),
        ),
        migrations.AddField(
            model_name='oneyou2page',
            name='twitter_card',
            field=models.CharField(default='summary', max_length=255),
        ),
        migrations.AddField(
            model_name='oneyou2page',
            name='twitter_description',
            field=models.CharField(default='Start the fight back to a healthier you! One You is packed with practical tips, tools and free apps to help you improve your health today', max_length=255),
        ),
        migrations.AddField(
            model_name='oneyou2page',
            name='twitter_image_fk',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.PHEImage', verbose_name='Twitter image'),
        ),
        migrations.AddField(
            model_name='oneyou2page',
            name='twitter_site',
            field=models.CharField(default='@OneYouPHE', max_length=255),
        ),
        migrations.AddField(
            model_name='oneyou2page',
            name='twitter_title',
            field=models.CharField(default='One You - Home', max_length=255),
        ),
        migrations.AddField(
            model_name='oneyou2page',
            name='twitter_url',
            field=models.CharField(default='https://www.nhs.uk/oneyou', max_length=255),
        ),
    ]
