# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-23 09:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0043_metatags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metatags',
            name='page',
        ),
        migrations.AddField(
            model_name='oneyou2page',
            name='og_description',
            field=models.CharField(default='Fun ideas, recipes, top tips and activities to help your kids stay healthy. Make a change today with Change4Life!', max_length=255),
        ),
        migrations.AddField(
            model_name='oneyou2page',
            name='og_image',
            field=models.CharField(default='https://www.nhs.uk/change4life/assets/c4l-generic-social-share-f6de41c98796bab1b40f263d13f5933cf68c295524b40ec7445aa2016aed156f.jpg', max_length=255),
        ),
        migrations.AddField(
            model_name='oneyou2page',
            name='og_title',
            field=models.CharField(default='Change4Life - Change4Life', max_length=255),
        ),
        migrations.AddField(
            model_name='oneyou2page',
            name='og_type',
            field=models.CharField(default='website', max_length=255),
        ),
        migrations.AddField(
            model_name='oneyou2page',
            name='og_url',
            field=models.CharField(default='https://www.nhs.uk/change4life', max_length=255),
        ),
        migrations.AddField(
            model_name='oneyou2page',
            name='twitter_card',
            field=models.CharField(default='summary', max_length=255),
        ),
        migrations.AddField(
            model_name='oneyou2page',
            name='twitter_description',
            field=models.CharField(default='Fun ideas, recipes, top tips and activities to help your kids stay healthy. Make a change today with Change4Life!', max_length=255),
        ),
        migrations.AddField(
            model_name='oneyou2page',
            name='twitter_image',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='oneyou2page',
            name='twitter_site',
            field=models.CharField(default='@Change4Life', max_length=255),
        ),
        migrations.AddField(
            model_name='oneyou2page',
            name='twitter_title',
            field=models.CharField(default='Change4Life - Change4Life', max_length=255),
        ),
        migrations.AddField(
            model_name='oneyou2page',
            name='twitter_url',
            field=models.CharField(default='https://www.nhs.uk/change4life', max_length=255),
        ),
        migrations.DeleteModel(
            name='MetaTags',
        ),
    ]
