# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-23 10:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0044_auto_20180323_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oneyou2page',
            name='twitter_image',
            field=models.CharField(default='https://www.nhs.uk/change4life/assets/c4l-generic-social-share-f6de41c98796bab1b40f263d13f5933cf68c295524b40ec7445aa2016aed156f.jpg', max_length=255),
        ),
    ]
