# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-23 14:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0045_auto_20180323_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oneyou2page',
            name='og_description',
            field=models.CharField(default='Start the fight back to a healthier you! One You is packed with practical tips, tools and free apps to help you improve your health today', max_length=255),
        ),
        migrations.AlterField(
            model_name='oneyou2page',
            name='og_image',
            field=models.CharField(default='https://campaignstorage.blob.core.windows.net/oneyou/production/section_page/social_image/1/5536388cbc87edbba77951fa802cf3f9.jpg', max_length=255),
        ),
        migrations.AlterField(
            model_name='oneyou2page',
            name='og_title',
            field=models.CharField(default='One You - Home', max_length=255),
        ),
        migrations.AlterField(
            model_name='oneyou2page',
            name='og_url',
            field=models.CharField(default='https://www.nhs.uk/oneyou', max_length=255),
        ),
        migrations.AlterField(
            model_name='oneyou2page',
            name='twitter_description',
            field=models.CharField(default='Start the fight back to a healthier you! One You is packed with practical tips, tools and free apps to help you improve your health today', max_length=255),
        ),
        migrations.AlterField(
            model_name='oneyou2page',
            name='twitter_image',
            field=models.CharField(default='https://campaignstorage.blob.core.windows.net/oneyou/production/section_page/social_image/1/5536388cbc87edbba77951fa802cf3f9.jpg', max_length=255),
        ),
        migrations.AlterField(
            model_name='oneyou2page',
            name='twitter_site',
            field=models.CharField(default='@OneYouPHE', max_length=255),
        ),
        migrations.AlterField(
            model_name='oneyou2page',
            name='twitter_title',
            field=models.CharField(default='One You - Home', max_length=255),
        ),
        migrations.AlterField(
            model_name='oneyou2page',
            name='twitter_url',
            field=models.CharField(default='https://www.nhs.uk/oneyou', max_length=255),
        ),
    ]
