# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-26 10:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0047_auto_20180322_1359'),
        ('pages', '0043_auto_20180325_1853'),
    ]

    operations = [
    ]
