# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-20 16:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0053_auto_20180420_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oneyou2page',
            name='og_url',
            field=models.CharField(blank=True, default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='oneyou2page',
            name='twitter_url',
            field=models.CharField(blank=True, default='', max_length=255),
            preserve_default=False,
        ),
    ]
