# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-05-23 13:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0058_auto_20180517_1740'),
        ('pages', '0055_auto_20180509_1343'),
    ]

    operations = [
    ]
