# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-05-29 09:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0058_auto_20180517_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='oneyou2page',
            name='use_share_button',
            field=models.BooleanField(default=True),
        ),
    ]
