# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-06-26 12:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0064_auto_20180612_2236'),
        ('pages', '0064_auto_20180613_1745'),
    ]

    operations = [
    ]
