# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-06-27 14:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0065_auto_20180618_1647'),
        ('pages', '0065_merge_20180626_1308'),
    ]

    operations = [
    ]
