# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-08-01 16:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0072_auto_20180726_0955'),
        ('pages', '0069_auto_20180716_1037'),
    ]

    operations = [
    ]
