# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-09-10 16:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0076_merge_20180904_0001'),
        ('pages', '0074_auto_20180828_1325'),
    ]

    operations = [
    ]
