# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-09-11 13:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0078_merge_20180911_1133'),
        ('pages', '0077_auto_20180905_1541'),
    ]

    operations = [
    ]
