# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-10-19 10:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0087_auto_20181019_1024'),
    ]

    operations = [
        migrations.AddField(
            model_name='footer',
            name='number_per_column',
            field=models.IntegerField(blank=True, default=4, help_text='Number of menu items per column', null=True),
        ),
    ]
