# Generated by Django 2.1.2 on 2018-12-17 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0092_auto_20181121_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipepage',
            name='host',
            field=models.CharField(blank=True, choices=[('brightcove', 'Brightcove'), ('wirewax', 'Wirewax')], default='brightcove', max_length=15, null=True),
        ),
    ]
