# Generated by Django 2.1.4 on 2019-01-09 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0093_auto_20181217_1427'),
        ('pages', '0093_auto_20181217_1337'),
    ]

    operations = [
    ]
