# Generated by Django 2.1.4 on 2019-01-29 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0094_merge_20190109_1038'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='footer',
            options={'verbose_name': 'Footer (OneYou)', 'verbose_name_plural': 'Footers (OneYou)'},
        ),
        migrations.AlterModelOptions(
            name='header',
            options={'verbose_name': 'Header (OneYou)', 'verbose_name_plural': 'Headers (OneYou)'},
        ),
        migrations.AlterModelOptions(
            name='menu',
            options={'verbose_name': 'Menu (OneYou)', 'verbose_name_plural': 'Menus (OneYou)'},
        ),
        migrations.AlterModelOptions(
            name='theme',
            options={'verbose_name': 'Theme (OneYou)', 'verbose_name_plural': 'Themes (OneYou)'},
        ),
    ]
