# Generated by Django 2.1.4 on 2019-02-04 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0095_auto_20190129_1217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='changehistory',
            name='page',
        ),
        migrations.DeleteModel(
            name='ChangeHistory',
        ),
    ]
