# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-20 16:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShelfAbstract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='A name to use in the CMS', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ShelfRevision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, verbose_name='created at')),
                ('content_json', models.TextField(verbose_name='content JSON')),
            ],
            options={
                'verbose_name': 'shelf revision',
                'verbose_name_plural': 'shelf revisions',
            },
        ),
        migrations.CreateModel(
            name='PromoShelf',
            fields=[
                ('shelfabstract_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shelves.ShelfAbstract')),
                ('heading', models.CharField(max_length=255)),
            ],
            bases=('shelves.shelfabstract',),
        ),
        migrations.AddField(
            model_name='shelfrevision',
            name='shelf',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='shelves.ShelfAbstract', verbose_name='shelf'),
        ),
        migrations.AddField(
            model_name='shelfrevision',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AddField(
            model_name='shelfabstract',
            name='live_revision',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='shelves.ShelfRevision', verbose_name='live revision'),
        ),
    ]
