# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-20 17:32
from __future__ import unicode_literals

from django.db import migrations, models
import shelves.models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('shelves', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shelfabstract',
            name='content_type',
            field=models.ForeignKey(default=2006, on_delete=models.SET(shelves.models.get_default_shelf_content_type), related_name='shelves', to='contenttypes.ContentType', verbose_name='content type'),
            preserve_default=False,
        ),
    ]
