# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-21 17:04
from __future__ import unicode_literals

from django.db import migrations, models
import shelves.models


class Migration(migrations.Migration):

    dependencies = [
        ('shelves', '0002_shelfabstract_content_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='promoshelf',
            name='button_text',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shelfabstract',
            name='content_type',
            field=models.ForeignKey(editable=False, on_delete=models.SET(shelves.models.get_default_shelf_content_type), related_name='shelves', to='contenttypes.ContentType', verbose_name='content type'),
        ),
    ]
