# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-21 17:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelves', '0003_auto_20180221_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='promoshelf',
            name='button_link',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
