# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-27 11:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shelves', '0008_auto_20180227_1028'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bannershelf',
            old_name='image',
            new_name='background_image',
        ),
    ]
