# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-27 12:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0040_page_draft_title'),
        ('shelves', '0009_auto_20180227_1126'),
    ]

    operations = [
        migrations.RenameField(
            model_name='promoshelf',
            old_name='button_text',
            new_name='cta_text',
        ),
        migrations.RemoveField(
            model_name='promoshelf',
            name='button_link',
        ),
        migrations.AddField(
            model_name='promoshelf',
            name='cta_link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='promoshelf',
            name='cta_page',
            field=modelcluster.fields.ParentalKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wagtailcore.Page'),
        ),
        migrations.AlterField(
            model_name='bannershelf',
            name='cta_page',
            field=modelcluster.fields.ParentalKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wagtailcore.Page'),
        ),
    ]
