# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-27 12:58
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('shelves', '0010_auto_20180227_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannershelf',
            name='cta_page',
            field=modelcluster.fields.ParentalKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='banner_shelf_links', to='wagtailcore.Page'),
        ),
        migrations.AlterField(
            model_name='promoshelf',
            name='cta_page',
            field=modelcluster.fields.ParentalKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promo_shelf_links', to='wagtailcore.Page'),
        ),
    ]
