# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-27 13:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shelves', '0011_auto_20180227_1258'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appteaser',
            old_name='iphone_line',
            new_name='iphone_link',
        ),
    ]
