# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-06 14:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shelves', '0012_auto_20180227_1333'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appteaser',
            old_name='iphone_link',
            new_name='cta_appstore',
        ),
        migrations.RenameField(
            model_name='appteaser',
            old_name='android_link',
            new_name='cta_googleplay',
        ),
    ]
