# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-19 10:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelves', '0014_auto_20180312_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appteaser',
            name='cta_appstore',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='appteaser',
            name='cta_googleplay',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='appteaser',
            name='heading',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bannershelf',
            name='cta_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bannershelf',
            name='heading',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='promoshelf',
            name='cta_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='promoshelf',
            name='heading',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
