# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-05-14 11:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelves', '0015_auto_20180319_1025'),
    ]

    operations = [
        migrations.AddField(
            model_name='bannershelf',
            name='meta_gradient',
            field=models.BooleanField(default=False, verbose_name='Green gradient'),
        ),
    ]
