# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-05-23 15:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
        ('shelves', '0016_bannershelf_meta_gradient'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeTeaser',
            fields=[
                ('shelfabstract_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shelves.ShelfAbstract')),
                ('heading', models.CharField(blank=True, max_length=255, null=True)),
                ('background_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.PHEImage')),
            ],
            bases=('shelves.shelfabstract',),
        ),
    ]
