# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-08-23 08:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelves', '0019_actionpanel'),
    ]

    operations = [
        migrations.AddField(
            model_name='appteaser',
            name='cta_link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
