# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-08-30 09:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shelves', '0021_auto_20180823_0914'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionSelf',
            fields=[
                ('shelfabstract_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shelves.ShelfAbstract')),
                ('paragon_id', models.IntegerField(unique=True)),
                ('paragon_action_code', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('position', models.IntegerField(unique=True)),
                ('action_code', models.CharField(max_length=255, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('rich_text_body', models.TextField(blank=True, null=True)),
                ('cta_type', models.CharField(blank=True, choices=[('direct_app', 'PHE App'), ('other_app', 'Other App'), ('one_link', 'One Link'), ('two_link', 'Two Links'), ('info_only', 'Info only')], default='direct_app', max_length=255, null=True)),
                ('cta1_text', models.CharField(blank=True, max_length=255, null=True)),
                ('cta1_link', models.CharField(blank=True, max_length=255, null=True)),
                ('cta2_text', models.CharField(blank=True, max_length=255, null=True)),
                ('cta2_link', models.CharField(blank=True, max_length=255, null=True)),
                ('cta_googleplay', models.CharField(blank=True, max_length=255, null=True)),
                ('cta_appstore', models.CharField(blank=True, max_length=255, null=True)),
                ('active', models.BooleanField(default=True, max_length=255)),
            ],
            bases=('shelves.shelfabstract',),
        ),
    ]
