# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-08-30 10:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shelves', '0022_actionself'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ActionSelf',
            new_name='ActionShelf',
        ),
    ]
