# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-08-30 15:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelves', '0023_auto_20180830_1119'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actionshelf',
            options={'verbose_name': 'Action', 'verbose_name_plural': 'Actions'},
        ),
        migrations.AlterField(
            model_name='actionshelf',
            name='action_code',
            field=models.CharField(help_text='Wirewax action code', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='actionshelf',
            name='category',
            field=models.CharField(help_text='Used by Paragon, can by anything.', max_length=255),
        ),
        migrations.AlterField(
            model_name='actionshelf',
            name='paragon_action_code',
            field=models.CharField(help_text='Must be unique, used by paragon. Designed to be a slug of title', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='actionshelf',
            name='paragon_id',
            field=models.IntegerField(help_text='Matches with the UID at paragon', unique=True),
        ),
        migrations.AlterField(
            model_name='actionshelf',
            name='position',
            field=models.IntegerField(help_text='Must be unique, this determines theorder paragon will return actionsin the email.', unique=True),
        ),
    ]
