# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-08-30 11:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shelves', '0023_auto_20180830_1119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actionpanel',
            name='shelfabstract_ptr',
        ),
        migrations.DeleteModel(
            name='ActionPanel',
        ),
    ]
