# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-09-10 15:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelves', '0024_auto_20180830_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='shelfabstract',
            name='tracking_group',
            field=models.CharField(blank=True, help_text='The tracking group, eg. EMM or OY', max_length=20, null=True),
        ),
    ]
