# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-09-17 11:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelves', '0026_auto_20180913_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionshelf',
            name='position',
            field=models.IntegerField(help_text='Must be unique, this determines theorder paragon will return actionsin the email.'),
        ),
        migrations.AlterUniqueTogether(
            name='actionshelf',
            unique_together=set([('category', 'position')]),
        ),
    ]
