# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-09-17 12:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelves', '0027_auto_20180917_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionshelf',
            name='action_code',
            field=models.CharField(blank=True, help_text='Wirewax action code', max_length=255, null=True),
        ),
    ]
