# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-09-19 09:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shelves', '0029_auto_20180917_1940'),
        ('shelves', '0027_auto_20180914_1228'),
    ]

    operations = [
    ]
