# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-10-16 10:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shelves', '0031_auto_20180919_2359'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bannershelf',
            options={'verbose_name': 'Banner Shelf (OneYou)', 'verbose_name_plural': 'Banner Shelves (OneYou)'},
        ),
    ]
