# Generated by Django 2.1.2 on 2018-12-17 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shelves', '0033_auto_20181107_1623'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appteaser',
            options={'verbose_name': 'App Teaser (OneYou)', 'verbose_name_plural': 'App Teasers (OneYou)'},
        ),
        migrations.AlterModelOptions(
            name='promoshelf',
            options={'verbose_name': 'Promo Shelf (OneYou)', 'verbose_name_plural': 'Promo Shelves (OneYou)'},
        ),
    ]
