# Generated by Django 2.1.4 on 2019-01-09 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shelves', '0034_auto_20181217_1427'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actionshelf',
            options={'verbose_name': 'Action (OneYou)', 'verbose_name_plural': 'Actions (OneYou)'},
        ),
    ]
