# Generated by Django 2.1.4 on 2019-01-09 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dctsharedcontent', '0002_auto_20181016_1143'),
        ('oneyou', '0003_auto_20190109_1247'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('sharedcontent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dctsharedcontent.SharedContent')),
                ('paragon_id', models.IntegerField(help_text='Matches with the UID at paragon', unique=True)),
                ('paragon_action_code', models.CharField(help_text='Must be unique, used by paragon. Designed to be a slug of title', max_length=255, unique=True)),
                ('category', models.CharField(choices=[('Be more active', 'Be more active'), ('Stay connected', 'Stay connected'), ('Reframing unhelpful thoughts', 'Reframing unhelpful thoughts'), ('Being in the present', 'Being in the present'), ('Get good sleep', 'Get good sleep'), ('Take control', 'Take control'), ('Healthy living', 'Healthy living'), ('Take action on my worries', 'Take action on my worries'), ('Do something for myself', 'Do something for myself'), ('Get help and support', 'Get help and support')], max_length=255)),
                ('position', models.IntegerField(help_text='Must be unique, this determines theorder paragon will return actionsin the email.')),
                ('action_code', models.CharField(help_text='Wirewax action code', max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('rich_text_body', models.TextField(blank=True, null=True)),
                ('cta_type', models.CharField(blank=True, choices=[('direct_app', 'PHE App'), ('other_app', 'Other App'), ('one_link', 'One Link'), ('two_link', 'Two Links'), ('info_only', 'Info only')], default='direct_app', max_length=255, null=True)),
                ('cta1_text', models.CharField(blank=True, max_length=255, null=True)),
                ('cta1_link', models.CharField(blank=True, max_length=255, null=True)),
                ('cta2_text', models.CharField(blank=True, max_length=255, null=True)),
                ('cta2_link', models.CharField(blank=True, max_length=255, null=True)),
                ('cta_googleplay', models.CharField(blank=True, max_length=255, null=True)),
                ('cta_appstore', models.CharField(blank=True, max_length=255, null=True)),
                ('active', models.BooleanField(default=True, max_length=255)),
            ],
            options={
                'verbose_name': 'Action',
                'verbose_name_plural': 'Actions',
            },
            bases=('dctsharedcontent.sharedcontent',),
        ),
        migrations.AlterUniqueTogether(
            name='action',
            unique_together={('category', 'position')},
        ),
    ]
