# Generated by Django 2.1.4 on 2019-01-14 11:33

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0040_page_draft_title'),
        ('images', '0002_pheimage_file_hash'),
        ('release', '0041_releasepage_submitted_for_moderation'),
        ('pages', '0094_merge_20190109_1038'),
        ('oneyou', '0007_auto_20190110_1732'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('tracking_group', models.CharField(blank=True, max_length=20, null=True)),
                ('og_title', models.CharField(default='Home', max_length=255)),
                ('og_description', models.CharField(default='Description', max_length=255)),
                ('og_url', models.CharField(blank=True, max_length=255)),
                ('og_type', models.CharField(default='website', max_length=255)),
                ('twitter_url', models.CharField(blank=True, max_length=255)),
                ('twitter_card', models.CharField(default='summary', max_length=255)),
                ('twitter_site', models.CharField(default='@TwitterUser', max_length=255)),
                ('twitter_title', models.CharField(default='Home', max_length=255)),
                ('twitter_description', models.CharField(default='Description', max_length=255)),
                ('use_share_button', models.BooleanField(default=True)),
                ('use_email_button', models.BooleanField(default=False)),
                ('use_print_button', models.BooleanField(default=False)),
                ('hide_from_breadcrumb', models.BooleanField(default=False)),
                ('recipe_name', models.CharField(blank=True, max_length=255, null=True)),
                ('tags', models.CharField(blank=True, max_length=255, null=True)),
                ('serves', models.IntegerField(default=0)),
                ('preparation_time', models.IntegerField(default=0)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=255)),
                ('ingredients_list', wagtail.core.fields.RichTextField(blank=True, null=True)),
                ('instructions', wagtail.core.fields.RichTextField(blank=True, null=True)),
                ('header_gradient', models.BooleanField(default=False)),
                ('video_id', models.CharField(blank=True, max_length=50, null=True)),
                ('host', models.CharField(blank=True, choices=[('brightcove', 'Brightcove'), ('wirewax', 'Wirewax')], default='brightcove', max_length=15, null=True)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.PHEImage')),
                ('og_image_fk', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.PHEImage', verbose_name='OG image')),
                ('release', models.ForeignKey(blank=True, default=None, limit_choices_to={'content_status': 0}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recipepage_pages', to='release.Release')),
                ('theme', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recipepage_pages', to='pages.Theme')),
                ('twitter_image_fk', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.PHEImage', verbose_name='Twitter image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page', models.Model),
        ),
    ]
