# Generated by Django 2.1.4 on 2019-02-11 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oneyou', '0015_auto_20190204_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipepage',
            name='header_image_desktop_rendition',
            field=models.CharField(choices=[('none', 'Use Original'), ('128x263', '128 x 263 [[oneyou]]'), ('128x378', '128 x 378 [[oneyou]]'), ('146x336', '146 x 336 [[oneyou]]'), ('182x378', '182 x 378 [[oneyou]]'), ('196x263', '196 x 263 [[oneyou]]'), ('196x289', '196 x 289 [[oneyou]]'), ('200x200', '200 x 200 [[oneyou]]'), ('224x336', '224 x 336 [[oneyou]]'), ('258x220', '258 x 220 [[oneyou]]'), ('280x289', '280 x 289 [[oneyou]]'), ('287x263', '287 x 263 [[oneyou]]'), ('364x220', '364 x 220 [[oneyou]]'), ('403x263', '403 x 263 [[oneyou]]'), ('410x263', '410 x 263 [[oneyou]]'), ('460x336', '460 x 336 [[oneyou]]'), ('504x263', '504 x 263 [[oneyou]]'), ('560x220', '560 x 220 [[oneyou]]'), ('575x263', '575 x 263 [[oneyou]]'), ('650x450', '650 x 450 [[oneyou]]'), ('720x263', '720 x 263 [[oneyou]]'), ('1440x240', '1440 x 240 [[oneyou]]'), ('1440x309', '1440 x 309 [[oneyou]]'), ('1440x800', '1440 x 800 [[oneyou]]'), ('1150x220', '1150 x 220 [[oneyou]]'), ('180x360', '180 x 360 Teaser [[sexhealth]]'), ('408x351', '408 x 351 Information [[sexhealth]]'), ('1366x591', '1366 x 591 Home page header background [[sexhealth]]'), ('1440x366', '1440 x 366 Page header, banner/promo background [[sexhealth]]')], default='none', max_length=10, verbose_name='Desktop Rendition'),
        ),
    ]
