# Generated by Django 2.1.2 on 2018-10-31 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sexhealth', '0018_auto_20181029_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sexhealthpage',
            name='release',
            field=models.ForeignKey(blank=True, default=None, limit_choices_to={'content_status': 0}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sexhealthpage_pages', to='release.Release'),
        ),
    ]
