# Generated by Django 2.1.2 on 2018-11-14 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sexhealth', '0019_auto_20181031_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='sexhealthpage',
            name='hide_from_breadcrumb',
            field=models.BooleanField(default=False),
        ),
    ]
