# Generated by Django 2.1.4 on 2019-01-29 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sexhealth', '0030_auto_20190129_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sexhealthpage',
            name='theme',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sexhealthpage_pages', to='pages.Theme'),
        ),
    ]
