# Generated by Django 2.1.4 on 2019-01-29 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dctcmsbase', '0006_footer_header_menu_theme'),
        ('sexhealth', '0032_articlesexhealthpage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlesexhealthpage',
            name='theme',
        ),
        migrations.RemoveField(
            model_name='sexhealthpage',
            name='theme',
        ),
        migrations.AddField(
            model_name='articlesexhealthpage',
            name='page_theme',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articlesexhealthpage_pages', to='dctcmsbase.Theme', verbose_name='theme'),
        ),
        migrations.AddField(
            model_name='sexhealthpage',
            name='page_theme',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sexhealthpage_pages', to='dctcmsbase.Theme', verbose_name='theme'),
        ),
    ]
