# Generated by Django 2.1.2 on 2019-02-13 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sexhealth', '0035_auto_20190206_1557'),
        ('sexhealth', '0035_auto_20190212_1614'),
    ]

    operations = [
    ]
